protected/controllers/StoreController.php
<?php
if (!isset($_SESSION)) { session_start(); }

class StoreController extends CController
{
	public $layout='store_tpl';	
	public $crumbsTitle='';
	public $theme_compression='';
	
	public function beforeAction($action)
	{
		//$cs->registerCssFile($baseUrl.'/css/yourcss.css'); 		
		if( parent::beforeAction($action) ) {			
			
			/** Register all scripts here*/
			if ($this->theme_compression==2){
				ScriptManagerCompress::RegisterAllJSFile();
			    ScriptManagerCompress::registerAllCSSFiles();
			   
				$compress_css = require_once 'assets/css/css.php';
			    $cs = Yii::app()->getClientScript();
			    Yii::app()->clientScript->registerCss('compress-css',$compress_css);
			} else {
			   ScriptManager::RegisterAllJSFile();
			   ScriptManager::registerAllCSSFiles();
			}
			return true;
		}
		return false;
	}
	
	public function accessRules()
	{		
		
	}
	
    public function filters()
    {
    	$this->theme_compression = getOptionA('theme_compression');
		if ($this->theme_compression==2){
	        $filters = array(  
	            array(
	                'application.filters.HtmlCompressorFilter',
	            ),  
	        );
	        return $filters;
		}
    }	
		
	public function init()
	{		
		 $name=Yii::app()->functions->getOptionAdmin('website_title');
		 if (!empty($name)){		 	
		 	 Yii::app()->name = $name;
		 }
		 		 
		 // set website timezone
		 $website_timezone=Yii::app()->functions->getOptionAdmin("website_timezone");		 
		 if (!empty($website_timezone)){		 	
		 	Yii::app()->timeZone=$website_timezone;
		 }		 		 
	}
	
	public function actionHome()
	{
		
	unset($_SESSION['voucher_code']);
        unset($_SESSION['less_voucher']);
        unset($_SESSION['google_http_refferer']); 
        $_SESSION['profile_page']="restrahome";
        
		if (isset($_GET['token'])){
			if (!empty($_GET['token'])){
			    //Yii::app()->functions->paypalSetCancelOrder($_GET['token']);
			}
		}
				
		$seo_title=Yii::app()->functions->getOptionAdmin('seo_home');
		$seo_meta=Yii::app()->functions->getOptionAdmin('seo_home_meta');
		$seo_key=Yii::app()->functions->getOptionAdmin('seo_home_keywords');
					
		if (!empty($seo_title)){
		   $seo_title=smarty('website_title',getWebsiteName(),$seo_title);
		   $this->pageTitle=$seo_title;
		   Yii::app()->functions->setSEO($seo_title,$seo_meta,$seo_key);
		}

		$restratype =  FunctionsV3::getAllRtype();
		$this->render('index',array(
		   'home_search_mode'=>getOptionA('home_search_mode'),
		   'enabled_advance_search'=> getOptionA('enabled_advance_search'),
		   'restratype'=>$restratype,

		));
	}
		


        public function actionDJ()
	{
		
	unset($_SESSION['voucher_code']);
        unset($_SESSION['less_voucher']);
        unset($_SESSION['google_http_refferer']); 
        $_SESSION['profile_page']="djhome";
        
		if (isset($_GET['token'])){
			if (!empty($_GET['token'])){
			    //Yii::app()->functions->paypalSetCancelOrder($_GET['token']);
			}
		}
				
		$seo_title=Yii::app()->functions->getOptionAdmin('seo_home');
		$seo_meta=Yii::app()->functions->getOptionAdmin('seo_home_meta');
		$seo_key=Yii::app()->functions->getOptionAdmin('seo_home_keywords');
					
		if (!empty($seo_title)){
		   $seo_title=smarty('website_title',getWebsiteName(),$seo_title);
		   $this->pageTitle=$seo_title;
		   Yii::app()->functions->setSEO($seo_title,$seo_meta,$seo_key);
		}

		$restratype =  FunctionsV3::getAllRtype();
		$musictype =  FunctionsV3::getMusicType();
		$this->render('djhome',array(
		   'home_search_mode'=>getOptionA('home_search_mode'),
		   'enabled_advance_search'=> getOptionA('enabled_advance_search'),
		   'theme_hide_how_works'=>getOptionA('theme_hide_how_works'),
		   'theme_hide_cuisine'=>getOptionA('theme_hide_cuisine'),
		   'disabled_featured_merchant'=>getOptionA('disabled_featured_merchant'),
		   'disabled_subscription'=>getOptionA('disabled_subscription'),
		   'theme_show_app'=>getOptionA('theme_show_app'),
		   'theme_app_android'=>FunctionsV3::prettyUrl(getOptionA('theme_app_android')),
		   'theme_app_ios'=>FunctionsV3::prettyUrl(getOptionA('theme_app_ios')),
		   'theme_app_windows'=>FunctionsV3::prettyUrl(getOptionA('theme_app_windows')),
		   'restratype'=>$restratype,
		   'musictype'=>$musictype,
		));
	}
		



       public function actionhappyhours()
	{
		
	unset($_SESSION['voucher_code']);
        unset($_SESSION['less_voucher']);
        unset($_SESSION['google_http_refferer']); 
        $_SESSION['profile_page']="djhome";
        
		if (isset($_GET['token'])){
			if (!empty($_GET['token'])){
			    //Yii::app()->functions->paypalSetCancelOrder($_GET['token']);
			}
		}
				
		$seo_title=Yii::app()->functions->getOptionAdmin('seo_home');
		$seo_meta=Yii::app()->functions->getOptionAdmin('seo_home_meta');
		$seo_key=Yii::app()->functions->getOptionAdmin('seo_home_keywords');
					
		if (!empty($seo_title)){
		   $seo_title=smarty('website_title',getWebsiteName(),$seo_title);
		   $this->pageTitle=$seo_title;
		   Yii::app()->functions->setSEO($seo_title,$seo_meta,$seo_key);
		}

		
		$this->render('happyhours',array(
		   'home_search_mode'=>getOptionA('home_search_mode'),
		   'enabled_advance_search'=> getOptionA('enabled_advance_search'),
		   'theme_hide_how_works'=>getOptionA('theme_hide_how_works'),
		   'theme_hide_cuisine'=>getOptionA('theme_hide_cuisine'),
		   'disabled_featured_merchant'=>getOptionA('disabled_featured_merchant'),
		   'disabled_subscription'=>getOptionA('disabled_subscription'),
		   'theme_show_app'=>getOptionA('theme_show_app'),
		   'theme_app_android'=>FunctionsV3::prettyUrl(getOptionA('theme_app_android')),
		   'theme_app_ios'=>FunctionsV3::prettyUrl(getOptionA('theme_app_ios')),
		   'theme_app_windows'=>FunctionsV3::prettyUrl(getOptionA('theme_app_windows')),
		));
	}
	
	public function actiondeals()
	{
		unset($_SESSION['voucher_code']);
        unset($_SESSION['less_voucher']);
        unset($_SESSION['google_http_refferer']); 
        $_SESSION['profile_page']="djhome";
        
		if (isset($_GET['token'])){
			if (!empty($_GET['token'])){
			    //Yii::app()->functions->paypalSetCancelOrder($_GET['token']);
			}
		}
				
		$seo_title=Yii::app()->functions->getOptionAdmin('seo_home');
		$seo_meta=Yii::app()->functions->getOptionAdmin('seo_home_meta');
		$seo_key=Yii::app()->functions->getOptionAdmin('seo_home_keywords');
					
		if (!empty($seo_title)){
		   $seo_title=smarty('website_title',getWebsiteName(),$seo_title);
		   $this->pageTitle=$seo_title;
		   Yii::app()->functions->setSEO($seo_title,$seo_meta,$seo_key);
		}

                $current_page_link=Yii::app()->createUrl('store/deals/',$current_page_get);
		$current_page_url='';
		
		$this->render('dealshome',array(
		   'home_search_mode'=>getOptionA('home_search_mode'),
		   'enabled_advance_search'=> getOptionA('enabled_advance_search'),
		   'theme_hide_how_works'=>getOptionA('theme_hide_how_works'),
		   'theme_hide_cuisine'=>getOptionA('theme_hide_cuisine'),
		   'disabled_featured_merchant'=>getOptionA('disabled_featured_merchant'),
		   'disabled_subscription'=>getOptionA('disabled_subscription'),
		   'theme_show_app'=>getOptionA('theme_show_app'),
		   'theme_app_android'=>FunctionsV3::prettyUrl(getOptionA('theme_app_android')),
		   'theme_app_ios'=>FunctionsV3::prettyUrl(getOptionA('theme_app_ios')),
		   'theme_app_windows'=>FunctionsV3::prettyUrl(getOptionA('theme_app_windows')),
		));
	}
	
	
	
	
	
		  
	public function actionIndex()
	{							
		$this->redirect(Yii::app()->request->baseUrl."/store/home");
		Yii::app()->end();		
	}
	
	public function actionBookingConfirmation()
	{							
		 $this->renderPartial('/store/booking-confirm', $data);	
	}	
	
	public function actionCuisine()
	{
		/*update merchant if expired and sponsored*/
		Yii::app()->functions->updateMerchantSponsored();
		Yii::app()->functions->updateMerchantExpired();
		
		/*$category='';
		$getdata=isset($_GET)?$_GET:'';
		if(is_array($getdata) && count($getdata)>=1){
			$category=$getdata['category'];
			$category=str_replace("-"," ",$category);
		}
		
		if ( $cat_res=Yii::app()->functions->GetCuisineByName($category)){
			$cuisine_id=$cat_res['cuisine_id'];
		 } else $cuisine_id="-1";
		 $filter_cuisine[]=$cuisine_id;*/
		
		$cuisine_id=isset($_GET['category'])?$_GET['category']:'';
		 
		 if (!isset($_GET['filter_cuisine'])){
		 	$_GET['filter_cuisine']='';
		 }
		 
		$_GET['filter_cuisine']=$_GET['filter_cuisine'].",$cuisine_id";
		 			 
	    $res=FunctionsV3::searchByMerchant(
		   'kr_search_category',
		   isset($_GET['st'])?$_GET['st']:'',
		   isset($_GET['page'])?$_GET['page']:0,
		   FunctionsV3::getPerPage(),
		   $_GET			  
		);
		
		$country_list=Yii::app()->functions->CountryList();
		$country=getOptionA('merchant_default_country');  
		if (array_key_exists($country,(array)$country_list)){
			$country_name = $country_list[$country];
		} else $country_name="United states";
				
		if ($lat_res=Yii::app()->functions->geodecodeAddress($country_name)){    		
    		$lat_res=array(
    		  'lat'=>$lat_res['lat'],
    		  'lng'=>$lat_res['long'],
    		);
    	} else {
    		$lat_res=array();
    	} 
    	
    	$cs = Yii::app()->getClientScript();
    	$cs->registerScript(
		  'country_coordinates',
		  'var country_coordinates = '.json_encode($lat_res).'
		  ',
		  CClientScript::POS_HEAD
		);
		
		$this->render('merchant-list-cuisine',array(
		  'list'=>$res,
		  'category'=>$category
		));
	}
	
	public function actionMusicType()
	{
	
		Yii::app()->functions->updateMerchantSponsored();
		Yii::app()->functions->updateMerchantExpired();
		
		/*$category='';
		$getdata=isset($_GET)?$_GET:'';
		if(is_array($getdata) && count($getdata)>=1){

protected/views/layouts/_store.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<head>

<!-- IE6-8 support of HTML5 elements --> 
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if IE]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width" />
<title><?php echo CHtml::encode($this->pageTitle); ?></title>
<link rel="shortcut icon" href="<?php echo  Yii::app()->request->baseUrl; ?>/favicon.ico?ver=1.0" />
<?php Widgets::analyticsCode();?>
</head>
<body>
<div class="content">
 <?php echo $content;?>
</div> <!--END content-->
<div class="footer-wrap" style="display:none;"></div>
<?php ScriptManager::registerGlobalVariables();?>
</body>
</html>

protected/views/layouts/front_bottom_footer.php
<section class="footer">
	
	<div class="container">
	
		<div class="row">
		
			<div class="col-sm-12 col-xs-12 text-center footer-content">
				<p>Download flipQ App</p>
				<p>Best way to Pre-Order Happy Hours</p>
			</div>
		  
			<div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4 col-xs-10 col-xs-offset-1 text-center">
			
				<div class="col-sm-6 col-xs-6">
					<a href="https://itunes.apple.com/" target="_blank">
						<img src="http://52.10.201.183/dev/flipq/images/appstore.png">
					</a>
				</div>
			
				<div class="col-sm-6 col-xs-6">
					<a href="https://play.google.com/" target="_blank">
						<img src="http://52.10.201.183/dev/flipq/images/googleplay.png">
					</a>
				</div>
			
			</div>
		
		</div>
		
		<hr>
		
		<div class="row  footer-content1">
			
			
		
			<div class="col-sm-4 col-xs-6">
		<?php 	if ($theme_hide_footer_section1!=2)
				{ ?>
					<h4><?php echo t("Menu")?></h4>
			<?php 	if (is_array($menu) && count($menu)>=1)
					{ ?>
				<?php	foreach ($menu as $val)
						{ ?>
							<!--
							<li>
				<a href="<?php //echo FunctionsV3::customPageUrl($val)?>" <?php FunctionsV3::openAsNewTab($val)?>><?php //echo $val['page_name']?></a>
							</li>
							--!> 
				<?php 	} ?>
					
						<li>
							<a href="/store/terms">Terms & Conditions</a>
						</li>
					
						<li>
							<a href="/store/policy">Privacy Policy</a>
						</li>
						<li>
							<a href="/store/calcallationpolicy">Cancellation Policy</a>
						</li>
						

						<li>
							<a href="/store/contact">Contact Us</a>
						</li>
			<?php	} ?>
		<?php	} ?>
			</div> <!--col-->
				  
			<div class="col-sm-4 col-xs-6">
		<?php 	if ($theme_hide_footer_section2!=2)
				{ ?>
				
					<h4><?php echo t("Others")?></h4>
					
	
			   
					<li><a href="<?php echo  Yii::app()->request->baseUrl; ?>/store/merchantsignupinfo?btype=restaurant">Restaurant Registration</a></li>
				 
					<li><a href="<?php echo  Yii::app()->request->baseUrl; ?>/store/merchantsignupinfo?btype=dj">Performing Artists/DJs Sign Up</a></li>

					<li><a href="<?php echo  Yii::app()->request->baseUrl; ?>/merchant/login">Restaurant Login</a></li>
					
		<?php 	} ?>  
			</div> <!--col-->
		 
		<?php 	if ($social_flag<>1)
				{ ?>
					<div class="col-sm-4 col-xs-6">
						<h4><?php echo t("Connect with us")?></h4>
						<div class="mytable social-wrap" style="text-align: left;">
					<?php	if (!empty($google_page))
							{?>
								<div class="mycol border">
									<a style="color:#D14836" target="_blank" href="<?php echo FunctionsV3::prettyUrl($google_page)?>"><i class="fa fa-google-plus"></i></a>
							   </div> <!--col-->
					<?php	} 
							
							if (!empty($twitter_page))
							{	?>
								<div class="mycol border">
									<a style="color:#00ACEE" target="_blank" href="<?php echo FunctionsV3::prettyUrl($twitter_page)?>"><i class="fa fa-twitter"></i></a>
							   </div> <!--col-->
					<?php	} ?>
	   
					<?php 	if (!empty($fb_page))
							{ ?>
							   <div class="mycol border">
								<a style="color:#3B5999" target="_blank" href="<?php echo FunctionsV3::prettyUrl($fb_page)?>"><i class="fa fa-facebook"></i></a>
							   </div> <!--col-->
					<?php 	} ?>
					   
						   
					<?php 	if (!empty($intagram_page))
							{ ?>
								<div class="mycol border">
									<a style="color:#3E729A" target="_blank" href="<?php echo FunctionsV3::prettyUrl($intagram_page)?>">
										<i class="fa fa-instagram"></i>
									</a>
								</div> <!--col-->
					<?php 	} ?>
						   
					<?php 	if (!empty($youtube_url))
							{	?>
								<div class="mycol border">
									<a style="color:#CC332D" target="_blank" href="<?php echo FunctionsV3::prettyUrl($youtube_url)?>">
										<i class="ion-social-youtube-outline"></i>
									</a>
								</div> <!--col-->
					<?php 	} ?>
						   
						</div> <!--social wrap-->
							 
					</div> <!--col-->
		<?php	} ?>
		 
		</div> <!--row-->
</section>

protected/views/layouts/front_footer.php
<?php 
	$check_login=Yii::app()->functions->isMerchantLogin();
	//if($check_login)
	//{} else {
		/*add global variables to footer*/
		ScriptManager::registerGlobalVariables();
		if(!$_SESSION['fq_search_address'])
		{ ?>
			<script>
			jQuery(window).load(function(){
				if( jQuery.cookie("Notshowdialog") != 'true' )
				{
					geolocate();
				}
			});
			</script>
<?php 	} else { ?>

			<script>
				jQuery(window).load(function(){
					jQuery('#global-place').text("<?php print $_SESSION['fq_search_address']; ?>");
				});
			</script>
<?php 	} ?>

	<script>
		jQuery(window).load(function(){
			jQuery('.location-selection a').click(function(){
				//alert();
				geolocate();
			})
		});
	</script>

	<?php
		$google_key=getOptionA('google_geo_api_key') ?>
		<script type="text/javascript" src="//maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=<?php print $google_key ?>"></script>
		<script src="//www.google.com/recaptcha/api.js?onload=onloadMyCallback&render=explicit" async defer ></script>
	<?php
	//} ?>
</body>

</html>

protected/views/layouts/front_header.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<head>

<!-- IE6-8 support of HTML5 elements --> 
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if IE]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, user-scalable=no">
<title><?php echo CHtml::encode($this->pageTitle); ?></title>
<link rel="shortcut icon" href="<?php echo  Yii::app()->request->baseUrl; ?>/favicon.ico?ver=1.1" />
<script type="text/javascript" src="/assets/vendor/jquery-1.10.2.min.js"></script>
<?php 
/*add the analytic codes */
Widgets::analyticsCode();
?>
<?php /* $geocode = Yii::app()->functions->geodecodeAddress($_GET['s']);  
	print_r($geocode);
 */ ?>

</head>
<body>

protected/views/layouts/front_top_menu.php
<?php $this->renderPartial('/front/modal');?>

<?php //$this->renderPartial('/front/modals'); ?>
<header>

<div class="loader"></div>
<section class="top-header">
    <div class="container-fluid">
		<div clas="row text-right">
			<div class="col-sm-7 col-sm-offset-5 col-md-6 col-md-offset-6 col-lg-5 col-lg-offset-7 col-xs-12 text-right">
				<ul>
					<li>support@flipq.in</li>
					<li>+91 9971234009</li>
				</ul>
			</div>
		</div>
    </div> <!-- container -->
</section> <!-- top-header -->
  
<section class="main-header">
	<div class="container leftlogo">
		<div class="row">
			<div class="col-lg-2 col-md-3 col-sm-3 col-xs-4">
				<?php
				if ( $theme_hide_logo<>2)
				{
					if ($_SESSION['profile_page']=='djhome')
					{ ?>
						<a href="<?php echo Yii::app()->createUrl('/store/home');?>" >
			<?php	} else { ?> 
						<a href="<?php echo Yii::app()->createUrl("/store/home");?>">
			<?php	} ?>
							<img src="<?php echo FunctionsV3::getDesktopLogo();?>" class="site-logo">
						</a>
		<?php	} ?>
			</div>
			
			<div class="col-lg-10 col-md-9 col-sm-9 text-right hidden-xs">
				<ul class="nav-main">
					
					<li><a href="/store/home">Home</a></li>
					<li><a href="/store/page/how-it-work">How It Works</a></li>
					<li><a id="open-location3"><span class="fa fa-map-marker position-abt text-white"></span>
                                        <?php
                                          if($_SESSION['fq_search_address'])
                                          {
                                           $address =  explode(',',$_SESSION['fq_search_address']);
                                           echo $address[0];
                                          }
                                          else
                                           echo 'Location';

                                         ?>
                                         </a>
						<!--<a id="open-location">
							<div class="global-search">
								<input type="hidden" value="-1" id="hdnGlobalCity">
								<span class="font13" id="global-place">Location </span>
								<span class="fa fa-map-marker position-abt text-white"></span>
							</div>
						</a>-->
					</li>
					<li>
				<?php	if($_SESSION['kr_client']['client_id'])
						{

							$cid  = $_SESSION['kr_client']['client_id']; ?>
							
							<a href="<?php echo Yii::app()->request->baseUrl."/store/profile"?>"><?php echo $_SESSION['kr_client']['first_name']?></a> | <a href="<?php echo Yii::app()->request->baseUrl."/store/Logout"?>">Logout</a>
				  <?php } else { ?>
							<a data-toggle="modal" data-target="#loginModal">Login | Register</a>
				  <?php } ?>
					</li>
					
					
				</ul>
			</div>
						
			<div class="col-xs-8 visible-xs text-right">
				<ul class="nav-main-xs">
					<li><a href="/store/home"><i class="fa fa-home" aria-hidden="true"></i></a></li>
					<li><a data-toggle="modal" data-target="#loginModal"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp; |&nbsp; <i class="fa fa-user-plus" aria-hidden="true"></i></a></li>
					<li><a id="open-location2"><i class="fa fa-map-marker" aria-hidden="true"></i></a></li>
				</ul>
			</div>
		</div>  <!-- row -->
    </div> <!-- container -->
</section> <!-- main-header -->
		
<section class="main-header sticky">
    <div class="container leftlogo">
		<div class="row">
        
			<div class="col-lg-2 col-md-2 col-sm-2 col-xs-4">
				<?php
				if ( $theme_hide_logo<>2)
				{
					if ($_SESSION['profile_page']=='djhome')
					{ ?>
						<a href="<?php echo Yii::app()->createUrl('/store/dj');?>" >
			<?php	} else { ?> 
						<a href="<?php echo Yii::app()->createUrl("/store");?>">
			<?php	} ?>
							<img src="<?php echo FunctionsV3::getDesktopLogo();?>" class="site-logo">
						</a>
		<?php	} ?>
			</div>
			<?php

if(Yii::app()->controller->action->id=='home' || Yii::app()->controller->action->id=='searchresult')
{
$styles = 'col-lg-5 col-md-5 col-sm-6 text-right hidden-xs';
?>
<div class="col-lg-5 col-md-5 col-sm-4 text-center hidden-xs">
          <input type="text" placeholder="Search Cusines, Restaurants, Pub ..." class="searchbar">
        </div>
<?php
}
else
{
$styles = 'col-lg-10 col-md-10 col-sm-10 text-right hidden-xs';
}

                        ?>
			<div class="<?php print $styles ?>">
				<ul class="nav-main">
				
					<li><a href="/store/home">Home</a></li>
					<li><a href="/store/page/how-it-work">How It Works</a></li>
					<li><span class="fa fa-map-marker position-abt text-white" style="color:#fff"></span>
						<a id="open-location"> <?php
                                          if($_SESSION['fq_search_address'])
                                          {
                                           $address =  explode(',',$_SESSION['fq_search_address']);
                                           echo $address[0];
                                          }
                                          else
                                           echo 'Location';

                                         ?></a>
					</li>
					<li>
				<?php	if($_SESSION['kr_client']['client_id'])
						{

							$cid  = $_SESSION['kr_client']['client_id']; ?>
							
							<a href="<?php echo Yii::app()->request->baseUrl."/store/profile"?>"><?php echo $_SESSION['kr_client']['first_name']?></a> | <a href="<?php echo Yii::app()->request->baseUrl."/store/Logout"?>">Logout</a>
				  <?php } else { ?>
							<a data-toggle="modal" data-target="#loginModal">Login | Register</a>
				  <?php } ?>
					</li>
							
					
			
				</ul>
			</div>
			
			<div class="col-xs-8 visible-xs text-right">
				
				<ul class="nav-main-xs">
				
					<li><a href="/store/home"><i class="fa fa-home" aria-hidden="true"></i></a></li>
					
					<li><a data-toggle="modal" data-target="#loginModal"><i class="fa fa-sign-in" aria-hidden="true"></i>&nbsp; |&nbsp; <i class="fa fa-user-plus" aria-hidden="true"></i></a></li>
					
					<li><a id="open-location4"><i class="fa fa-map-marker" aria-hidden="true"></i></a></li>
				
				</ul>
			</div>
		
		</div> <!-- row -->
    
	</div> <!-- container -->

</section> <!-- main-header sticky -->	
</header>
	

<?php  require_once('modals.php'); ?>

protected/views/layouts/mobile_tpl.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="en">
<head>

<!-- IE6-8 support of HTML5 elements --> 
<!--[if lt IE 9]>
<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!--[if IE]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
<title><?php echo CHtml::encode($this->pageTitle); ?></title>
<link rel="shortcut icon" href="<?php echo  Yii::app()->request->baseUrl; ?>/favicon.ico?ver=1.1" />
<?php 
/*add the analytic codes */
Widgets::analyticsCode();
?>
</head>
<body>
<?php echo $content;?>
</body>
</html>